const ERROR_ON_SAVE_DATA = 400;
const ERROR_UNAUTHORIZED = 401;
const ERROR_UNFORBIDDEN = 403;
const ERROR_NOT_FOUND = 404;
const ERROR_ON_VALIDATE_DATA = 422;
const ERROR_INTERNAL_SERVER = 500;

const ErrorsCode = {
  ERROR_ON_SAVE_DATA,
  ERROR_UNAUTHORIZED,
  ERROR_UNFORBIDDEN,
  ERROR_NOT_FOUND,
  ERROR_ON_VALIDATE_DATA,
  ERROR_INTERNAL_SERVER
};

export default ErrorsCode;
